In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Yes, there is a difference in the data types of the variables list_ and array_list. The list_ variable contains Python strings, while the array_list variable contains NumPy's string data type. You can print the data types of both variables using the type() function

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of elements in list_:")
for item in list_:
    print(type(item))
    
print("\n Data type of elements in array_list:")
for item in array_list:
    print(type(item))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

 Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.


Yes, there will be a difference in the data type of the elements present in both variables list_ and array_list when you create array_list with dtype=int. The elements in list_ are originally strings, but when you specify the dtype as int, the elements in array_list will be converted to integers.

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape

(ii) size

In [5]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [6]:
num_array.shape

(2, 3)

In [7]:
num_array.size

6

In [8]:
np.shape(num_array)

(2, 3)

In [9]:
np.size(num_array)

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [10]:
array = np.zeros((3,3))

In [11]:
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
import numpy.matlib as nm

In [13]:
matrix = nm.zeros((3,3))

In [14]:
matrix

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [15]:
array = np.eye(5)

In [16]:
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
matrix = nm.eye(5)

In [18]:
matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### The End